id: P009463
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7939
  title: ངག་དབང་བཀྲ་ཤིས་ཀྱི་རྣམ་ཐར་ཟུང་འཇུག་གྲུབ་པའི་རྔ་ཆེན་
  author: ''
  volumes:
    03f73cae950540d1ba2cbf9e4e5d683d:
      image_group_id: I1KG3456
      title: ''
      volume_number: 1
      total_pages: 98
