id: P009463
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:39:58.082208
source_metadata:
  id: bdr:W2CZ7939
  title: ངག་དབང་བཀྲ་ཤིས་ཀྱི་རྣམ་ཐར་ཟུང་འཇུག་གྲུབ་པའི་རྔ་ཆེན་
  author: ''
  volumes:
    03f73cae950540d1ba2cbf9e4e5d683d:
      image_group_id: I1KG3456
      title: ''
      volume_number: 1
      total_pages: 98
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
