id: I6236C68B
legacy_id: P009463
ocr_import_info:
  bdrc_scan_id: W2CZ7939
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T13:02:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:30:36.075784+00:00'
last_modified: 2022-09-02 23:30:55.416035
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7939
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7939
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ངག་དབང་བཀྲ་ཤིས་ཀྱི་རྣམ་ཐར་ཟུང་འཇུག་གྲུབ་པའི་རྔ་ཆེན།
  author: བསེ་ཚང ༠༥་བློ་བཟང་བཀྲ་ཤིས་འཕྲིན་ལས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5251333624039825
  ocr_word_median_confidence_index: 0.47999998927116394
quality: null
bases:
  I1KG3456:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3456
      total_pages: 98
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3456.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5251333624039825
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
